spring.application.name=cave-a-vin

#Connexion a la base de donnees
spring.datasource.url=jdbc:sqlserver://localhost;databasename=CAVE_A_VIN;integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=Pa$$w0rd

#D?tail des requetes pour le developpement
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.messages.encoding=UTF-8
spring.web.locale=en